### ISSUE TITLE
Create a database of plants

### ISSUE THREAD

**Issue by CLBaxter-W** [CLBaxter-W/Capstone-BotanicaGardenscape-Server#1]
Use Prisma or SQL to create db of 

- [x] users, 
- [x] plants, 
- [x] garden, 
- [x] cart - user/plant_inventory
- [x] user_role;
- [x] shape;
- [x] zone;
- [x]  water_requirement;
- [x]  sun_requirement;
- [x] soil_requirement;
- [x] growth_habit;
- [x] life_cycle;
- [x] address;
- [x]  garden_dimensions;
- [x] garden_plant;
- [x] plant_inventory

**Comment by Drewhastings123** [comment]
all databases created
